[package]
name = "rust-sdl2-wasm"
version = "0.1.0"
authors = ["Valerio Santinelli <santinelli@altralogica.it>"]
edition = "2021"

[dependencies]
sdl2 = { version='0.35.2', features = ["unsafe_textures"]}
gl = "0.14.0"

[[bin]]
name = "main"
path = "src/main.rs"
